### ISSUE TITLE
The "trashAssetsBeforeHeadlessRuns" option has been renamed and its replacement doesn't work

### ISSUE THREAD

**Issue by gergo-papp** [julianburr/cypress-match-screenshot#16]
I get the following error when starting cypress with the `trashAssetsBeforeHeadlessRuns ` option set in `cypress.json`:

> Can't start server
> A configuration option you have supplied has been renamed.
> 
> Please rename trashAssetsBeforeHeadlessRuns to trashAssetsBeforeRuns

Renaming to `trashAssetsBeforeRuns` fixes the errors but my old images (captured from previous runs) are always replaced by new caputures

**Comment by gergo-papp** [comment]
- package.json:
```json
"scripts": {
        "other stuff": "...",
    "cypress": "cypress run --record false",
        "other stuff": "...",
  },
  "devDependencies": {
        "other stuff": "...",
    "cypress": "^3.1.1",
    "cypress-match-screenshot": "^1.1.0",
        "other stuff": "...",
}
```
- cypress.json
```json
{
    "baseUrl": "http://localhost:8001",
    "trashAssetsBeforeRuns": false
}
```
- test
```javascript
describe('Visual Tests', function () {
    it('Home', function () {
        cy.visit('/');
        cy.matchScreenshot('Home');
    })

    it('FAQ page', function () {
        cy.visit('/faq');
        cy.matchScreenshot('FAQ');
    })
})
```

**Comment by gergo-papp** [comment]
I had some bad configuration...

**Comment by akoidan** [comment]
@gergo-papp how did you fix it? 
With `--record false` ? But I still want to have video records of my test, how it that related with matching screenshots?
